// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9YQI7thjxsiKtp-vKc2Py9RXy8BwN-6s',
    appId: '1:1059947667065:web:881e2c6a3746c16576bea8',
    messagingSenderId: '1059947667065',
    projectId: 'trackit-007',
    authDomain: 'trackit-007.firebaseapp.com',
    storageBucket: 'trackit-007.firebasestorage.app',
    measurementId: 'G-KXEZ8ERET5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0_M2Cctc3-DjTaE_gIc2N8nOoo2UZy7A',
    appId: '1:1059947667065:android:24b3289c95db42a576bea8',
    messagingSenderId: '1059947667065',
    projectId: 'trackit-007',
    storageBucket: 'trackit-007.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9YQI7thjxsiKtp-vKc2Py9RXy8BwN-6s',
    appId: '1:1059947667065:web:6d20a248c360ad9076bea8',
    messagingSenderId: '1059947667065',
    projectId: 'trackit-007',
    authDomain: 'trackit-007.firebaseapp.com',
    storageBucket: 'trackit-007.firebasestorage.app',
    measurementId: 'G-8946HYZ3NZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs5TebVg1G8k3C0vpmEb2ZC1871eukdJU',
    appId: '1:1059947667065:ios:d0c058889fef66fe76bea8',
    messagingSenderId: '1059947667065',
    projectId: 'trackit-007',
    storageBucket: 'trackit-007.firebasestorage.app',
    androidClientId: '1059947667065-bg60rck2j94uhdghcul3reonppanln91.apps.googleusercontent.com',
    iosClientId: '1059947667065-lma0nhi0de2r7mei0fjrqr2476viebna.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackit',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs5TebVg1G8k3C0vpmEb2ZC1871eukdJU',
    appId: '1:1059947667065:ios:7523cde7e6237b9176bea8',
    messagingSenderId: '1059947667065',
    projectId: 'trackit-007',
    storageBucket: 'trackit-007.firebasestorage.app',
    androidClientId: '1059947667065-bg60rck2j94uhdghcul3reonppanln91.apps.googleusercontent.com',
    iosClientId: '1059947667065-cs4vak2d44kg9c029tao8kj1p3sn54rh.apps.googleusercontent.com',
    iosBundleId: 'com.mosses.trackit',
  );

}