// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9YQI7thjxsiKtp-vKc2Py9RXy8BwN-6s',
    appId: '1:1059947667065:web:881e2c6a3746c16576bea8',
    messagingSenderId: '1059947667065',
    projectId: 'trackit-007',
    authDomain: 'trackit-007.firebaseapp.com',
    storageBucket: 'trackit-007.firebasestorage.app',
    measurementId: 'G-KXEZ8ERET5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0_M2Cctc3-DjTaE_gIc2N8nOoo2UZy7A',
    appId: '1:1059947667065:android:2502d7bae76cf0fd76bea8',
    messagingSenderId: '1059947667065',
    projectId: 'trackit-007',
    storageBucket: 'trackit-007.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9YQI7thjxsiKtp-vKc2Py9RXy8BwN-6s',
    appId: '1:1059947667065:web:6d20a248c360ad9076bea8',
    messagingSenderId: '1059947667065',
    projectId: 'trackit-007',
    authDomain: 'trackit-007.firebaseapp.com',
    storageBucket: 'trackit-007.firebasestorage.app',
    measurementId: 'G-8946HYZ3NZ',
  );
}
