name: Sentinel Security Scan

on: [pull_request]

jobs:
  risk_assessment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout Target Code
        uses: actions/checkout@v3

      - name: Run OSS PR AI
        uses: mossesross/oss-pr-ai-2@main 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
